### ISSUE TITLE
Unable to access the API from cross domain

### ISSUE THREAD

**Issue by sharmad-nachnolkar** [wsizoo/game-of-thrones-quotes#1]
This header [Access-Control-Allow-Origin:*] is not present on the response.
Hence I am getting a Cross Origin Error. Could you please add the below headers on the response.

Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:*

**Comment by wsizoo** [comment]
Thank you for brining this to my attention. I have pushed an update to allow CORS.
