### ISSUE TITLE
more quotes

### ISSUE THREAD

**Issue by moeinrahimi** [wsizoo/game-of-thrones-quotes#3]
hi 
this is a good api you have made, it would be much better if there were more quotes.
is there any way I can help to achieve that?

**Comment by ericdorsey** [comment]
@moeinrahimi 
Seems adding to (submitting a pull request) below file would be part of it?  

https://github.com/wsizoo/game-of-thrones-quotes/blob/master/db/seeds.rb

**Comment by moeinrahimi** [comment]
@ericdorsey 
thank you, as soon as I can I will send a pull request with more quotes.
